name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2.4.0

    - name: Set up Node
      uses: actions/setup-node@v2.5.0
      with:
        node-version: 16

    - name: Install dependencies with Yarn
      run: yarn

    - name: Run unit tests
      run: yarn run test:unit

    - name: Run linting
      run: yarn run lint

  browser-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2.4.0

    - name: Set up Node
      uses: actions/setup-node@v2.5.0
      with:
        node-version: 16

    - name: Install dependencies with Yarn
      run: yarn

    - name: Start local website server
      run: |
        yarn start &
        sleep 5

    - name: Run browser tests
      # Don't run these tests on forks. It would be nice to instead check
      # to see if the Sauce Labs environment variables are defined, but that
      # doesn't seem currently possible:
      # https://github.com/actions/runner/issues/520
      if: ${{ github.repository_owner == 'cfpb' }}
      run: yarn run cypress run && yarn run cypress run-ct
